### ISSUE TITLE
Auto close popup window

### ISSUE THREAD

**Issue by rtvbnl** [wallabag/firefox-ext#17] opened 2015-06-05 12:30 UTC
Enhancement:

After the page has been added to wallabag, automatically close the popup window after x seconds.

(Now I have to use Cmd+W every time)

**Comment by tcitworld** [comment] 2015-06-05 14:12
Normally there's autoclose that works, but I think something changed on wallabag's server side, so we need to change it too here.

**Comment by robertvanbregt** [comment] 2015-06-05 15:37
This is my bookmarklet:

<pre>
javascript:if(top['bookmarklet-url@wallabag.org']){top['bookmarklet-url@wallabag.org'];}else{(function(){var%20url%20=%20location.href%20||%20url;window.open('http://example.com/wallabag/?action=add&autoclose=true&url='%20+%20btoa(url),'_blank');})();void(0);}
</pre>
(I replaced my server with `example.com`)

So I guess inserting `&autoclose=true` to the call should do.

**Comment by tcitworld** [comment] 2015-06-05 16:23
That's what I'm talking about, yes.

**Comment by esion** [comment] 2016-01-29 07:28
I've just updated to 2.0.0 

I saw the option to autoclose (but did'nt check) 
Now ctrl+W don't work anymore (nor F12, nor right click)

I'm Debian 8, iceweasel 38.4 (default in debian) and official firefox 43

PS: ctrl+w when extension is not yet configured (I'll open another issue for that)

**Comment by stepardo** [comment] 2016-01-29 19:52
> I saw the option to autoclose (but did'nt check) .

So did you use the option or not? When this option is enabled wallabag attempts to close the window. Do you have javascript enabled?

**Comment by esion** [comment] 2016-01-29 20:24
Yes I have javascript, I tried the autoclose option + tab option, nothing happen, but it worked when disabling tab.

**Comment by stepardo** [comment] 2016-01-29 20:33
Yes, if tabs are used, the autoclose option will not work, and for me that is like I would expect it to work.

So the window does close when "autoclose" is enabled? Does that mean your problem is fixed, or shall the tab get closed as well?

**Comment by esion** [comment] 2016-01-29 21:15
ok with autoclosing, 
the fact we can check both autoclosing and tab is a bit disturbing, there's enhancement here.

The boring thing is when autoclosing and tabs are disabled, we have a popup that can't be closed

![capture d ecran de 2016-01-29 22 13 29](https://cloud.githubusercontent.com/assets/65737/12688305/a0615034-c6d5-11e5-9ba3-2cbdc840797c.png)

the only way is to use Alt+F4 (that is obviously not intuitive)

**Comment by stepardo** [comment] 2016-01-30 12:49
Ok, that the dialog window does not sport a proper titlebar with a close button seems to be caused by your setup (gnome3 + window manager).

I will change the description of the "autoclose" option to state specifically that only the dialog window will be closed. Secondly, I will change the default value of the "autoclose" setting to true.

**Comment by stepardo** [comment] 2016-02-01 20:30
Fixed with #35.

**Closed by stepardo** 2016-02-01 20:30 UTC
Labels: bug
